export { Button } from "./button";
export { Heading1 } from "./heading1";
export { Heading2 } from "./heading2";
export { Heading3 } from "./heading3";
export { Heading4 } from "./heading4";
export { Apple } from './svg' ;
export { GooglePlay } from './svg' ;
export { Facebook } from './svg' ;
export { Twitter } from './svg' ;
export { Instagram } from './svg' ;